from .rectangles_intersection import rectangle_intersection
from .rectangles_intersection import formingTuple
from .rectangles_intersection import sortedTuple

from .recursion_phone_mnemonics import phone_mnemonics
